In [10]:
import pandas as pd

JOIN_KEYS = [ "student_id", "degree_id", "part_id"]
df_crg=pd.read_parquet('D:\AI\Real projects\Academic_Advisor\data\preprocessed\V_CRG_STUDENT_COURSE\clean_v_crg_student_course.parquet')
print("="*80)
print("CRG BASIC INFO")
print("="*80)
print("Shape:", df_crg.shape)
print(df_crg.info())
print("\nColumns:")
print(df_crg.columns.tolist())

print("\nCRG join-key null counts:")
print(df_crg[JOIN_KEYS].isna().sum())

print("\nCRG join-key dtypes:")
print(df_crg[JOIN_KEYS].dtypes)

print("\nCRG sample join keys:")
display(df_crg[JOIN_KEYS + ["course_id", "student_course_id"]].head(20))

print("\nCRG unique counts:")
print(df_crg[JOIN_KEYS].nunique(dropna=False))

print("\nCRG duplicate count on student-course grain:")
crg_grain = JOIN_KEYS + ["course_id"]
print(df_crg.duplicated(crg_grain, keep=False).sum())

print("\nCRG duplicate examples on student-course grain:")
display(
    df_crg.loc[df_crg.duplicated(crg_grain, keep=False), 
               crg_grain + ["student_course_id", "grade_id", "final_mark", "points", "finish_status", "register_status"]]
    .sort_values(crg_grain)
    .head(50)
)

================================================================================
CRG BASIC INFO
================================================================================
Shape: (761347, 21)
<class 'pandas.DataFrame'>
RangeIndex: 761347 entries, 0 to 761346
Data columns (total 21 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   student_course_id      761347 non-null  string
 1   student_id             761347 non-null  string
 2   course_id              761347 non-null  string
 3   part_id                761347 non-null  Int64
 4   degree_id              761347 non-null  string
 5   faculty_id             761347 non-null  string
 6   grade_id               761347 non-null  string
 7   final_mark             761347 non-null  Int64
 8   points                 761347 non-null  Float64
 9   finish_status          761347 non-null  category
 10  course_outcome_status  761347 non-null  category
 11  register_status        761347 non-null  category
 12  in_credits             761347 non-null  category
 13  in_gpa                 761347 non-null  category
 14  in_agpa                761347 non-null  category
 15  study_mode             761347 non-null  category
 16  course_credits         761347 non-null  Float64
 17  course_name_sl         761347 non-null  string
 18  degree_name_sl         761347 non-null  string
 19  attempt_number         761347 non-null  Int64
 20  attempt_count          761347 non-null  Int64
dtypes: Float64(2), Int64(4), category(7), string(8)
memory usage: 177.4 MB
None

Columns:
['student_course_id', 'student_id', 'course_id', 'part_id', 'degree_id', 'faculty_id', 'grade_id', 'final_mark', 'points', 'finish_status', 'course_outcome_status', 'register_status', 'in_credits', 'in_gpa', 'in_agpa', 'study_mode', 'course_credits', 'course_name_sl', 'degree_name_sl', 'attempt_number', 'attempt_count']

CRG join-key null counts:
student_id    0
degree_id     0
part_id       0
dtype: int64

CRG join-key dtypes:
student_id    string
degree_id     string
part_id        Int64
dtype: object

CRG sample join keys:

   student_id degree_id  part_id course_id student_course_id
0   10000.111     3.111    20152  1016.111        939272.111
1   10000.111     3.111    20153  1017.111        953865.111
2   10000.111     3.111    20171  1019.111       1076397.111
3   10000.111     3.111    20152   431.111        925010.111
4   10000.111     3.111    20151   432.111        901340.111
5   10000.111     3.111    20161   433.111        973921.111
6   10000.111     3.111    20153   434.111        949219.111
7   10000.111     3.111    20171   435.111       1076396.111
8   10000.111     3.111    20173   436.111       1131540.111
9   10000.111     3.111    20182   437.111       1192637.111
10  10000.111     3.111    20171   438.111       1076398.111
11  10000.111     3.111    20183   443.111       1227299.111
12  10000.111     3.111    20171   451.111       1076557.111
13  10000.111     3.111    20173   466.111       1129422.111
14  10000.111     3.111    20181   466.111       1168332.111
15  10000.111     3.111    20183   467.111       1227298.111
16  10000.111     3.111    20151   501.111        901338.111
17  10000.111     3.111    20152   502.111        925007.111
18  10000.111     3.111    20162   503.111       1012727.111
19  10000.111     3.111    20161   504.111        982594.111

CRG unique counts:
student_id    16171
degree_id        52
part_id          66
dtype: int64

CRG duplicate count on student-course grain:
0

CRG duplicate examples on student-course grain:

Empty DataFrame
Columns: [student_id, degree_id, part_id, course_id, student_course_id, grade_id, final_mark, points, finish_status, register_status]
Index: []

In [11]:
df_add=pd.read_parquet(r'D:\AI\Real projects\Academic_Advisor\data\preprocessed\V_ADD_STUDENT_DEGREE_STATUS\clean_v_add_student_degree_status.parquet')
print("="*80)
print("ADD BASIC INFO")
print("="*80)
print("Shape:", df_add.shape)
print(df_add.info())
print("\nColumns:")
print(df_add.columns.tolist())

print("\nADD join-key null counts:")
print(df_add[JOIN_KEYS].isna().sum())

print("\nADD join-key dtypes:")
print(df_add[JOIN_KEYS].dtypes)

print("\nADD sample join keys:")
display(df_add[JOIN_KEYS + ["student_status_id"]].head(20))

print("\nADD unique counts:")
print(df_add[JOIN_KEYS].nunique(dropna=False))

print("\nADD duplicate count on semester snapshot grain:")
print(df_add.duplicated(JOIN_KEYS, keep=False).sum())

print("\nADD duplicate examples on semester snapshot grain:")
display(
    df_add.loc[df_add.duplicated(JOIN_KEYS, keep=False),
               JOIN_KEYS + ["student_status_id", "finish_status", "start_part_id", "finish_part_id"]]
    .sort_values(JOIN_KEYS)
    .head(50)
)

================================================================================
ADD BASIC INFO
================================================================================
Shape: (179844, 41)
<class 'pandas.DataFrame'>
RangeIndex: 179844 entries, 0 to 179843
Data columns (total 41 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   student_status_id       179844 non-null  string
 1   student_id              179844 non-null  string
 2   part_id                 179844 non-null  Int64
 3   degree_id               179844 non-null  string
 4   start_part_id           179844 non-null  Int64
 5   finish_part_id          115488 non-null  Int64
 6   grade_version_id        179844 non-null  string
 7   prev_gpa_points         163750 non-null  Float64
 8   prev_gpa_percent        163750 non-null  Float64
 9   gpa_points              179844 non-null  Float64
 10  gpa_percent             179844 non-null  Float64
 11  start_agpa_points       179844 non-null  Float64
 12  start_agpa_percent      179844 non-null  Float64
 13  end_agpa_points         179844 non-null  Float64
 14  end_agpa_percent        179844 non-null  Float64
 15  semester_reg_courses    179844 non-null  Float64
 16  semester_reg_credits    179844 non-null  Float64
 17  semester_pass_courses   179844 non-null  Float64
 18  semester_pass_credits   179844 non-null  Float64
 19  semester_fail_courses   179844 non-null  Float64
 20  semester_fail_credits   179844 non-null  Float64
 21  semester_in_courses     179844 non-null  Float64
 22  semester_in_credits     179844 non-null  Float64
 23  start_total_in_courses  179844 non-null  Float64
 24  start_total_in_credits  179844 non-null  Float64
 25  end_total_in_courses    179844 non-null  Float64
 26  end_total_in_credits    179844 non-null  Float64
 27  total_semesters         179844 non-null  Float64
 28  reg_total_semesters     179238 non-null  Float64
 29  total_reg_courses       179844 non-null  Float64
 30  total_reg_credits       179844 non-null  Float64
 31  total_pass_courses      179844 non-null  Float64
 32  total_pass_credits      179844 non-null  Float64
 33  total_fail_courses      179844 non-null  Float64
 34  total_fail_credits      179844 non-null  Float64
 35  finish_status           115801 non-null  string
 36  version_title_sl        179844 non-null  string
 37  degree_name_sl          179844 non-null  string
 38  degree_credits_count    179844 non-null  Float64
 39  start_level_id          178963 non-null  string
 40  start_level_name_pl     179844 non-null  string
dtypes: Float64(29), Int64(3), string(9)
memory usage: 82.0 MB
None

Columns:
['student_status_id', 'student_id', 'part_id', 'degree_id', 'start_part_id', 'finish_part_id', 'grade_version_id', 'prev_gpa_points', 'prev_gpa_percent', 'gpa_points', 'gpa_percent', 'start_agpa_points', 'start_agpa_percent', 'end_agpa_points', 'end_agpa_percent', 'semester_reg_courses', 'semester_reg_credits', 'semester_pass_courses', 'semester_pass_credits', 'semester_fail_courses', 'semester_fail_credits', 'semester_in_courses', 'semester_in_credits', 'start_total_in_courses', 'start_total_in_credits', 'end_total_in_courses', 'end_total_in_credits', 'total_semesters', 'reg_total_semesters', 'total_reg_courses', 'total_reg_credits', 'total_pass_courses', 'total_pass_credits', 'total_fail_courses', 'total_fail_credits', 'finish_status', 'version_title_sl', 'degree_name_sl', 'degree_credits_count', 'start_level_id', 'start_level_name_pl']

ADD join-key null counts:
student_id    0
degree_id     0
part_id       0
dtype: int64

ADD join-key dtypes:
student_id    string
degree_id     string
part_id        Int64
dtype: object

ADD sample join keys:

   student_id degree_id  part_id student_status_id
0      48.111    22.111    20203        297550.111
1      48.111    22.111    20211        314343.111
2      48.111    22.111    20212        320948.111
3     128.111    19.111    20111        114381.111
4     128.111    19.111    20112        114382.111
5     128.111    19.111    20121        213711.111
6     128.111    19.111    20122        144893.111
7     128.111    19.111    20131        114383.111
8     128.111    19.111    20132        203128.111
9     128.111    19.111    20133        113733.111
10    128.111    19.111    20141        113734.111
11    128.111    19.111    20142        214969.111
12    128.111    19.111    20151        202549.111
13    129.111    19.111    20111        113735.111
14    129.111    19.111    20112        113736.111
15    129.111    19.111    20121        113737.111
16    129.111    19.111    20122        113738.111
17    129.111    19.111    20131        150498.111
18    129.111    19.111    20132        150499.111
19    129.111    19.111    20133        150500.111

ADD unique counts:
student_id    16171
degree_id        52
part_id          71
dtype: int64

ADD duplicate count on semester snapshot grain:
0

ADD duplicate examples on semester snapshot grain:

Empty DataFrame
Columns: [student_id, degree_id, part_id, student_status_id, finish_status, start_part_id, finish_part_id]
Index: []

In [12]:
id_cols_crg = [ "student_id", "degree_id", "part_id", "course_id", "student_course_id"]
id_cols_add = [ "student_id", "degree_id", "part_id", "student_status_id"]

print("="*80)
print("CRG ID SAMPLE VALUES")
print("="*80)
for col in id_cols_crg:
    if col in df_crg.columns:
        print(f"\n{col}")
        print(df_crg[col].dropna().astype(str).head(20).tolist())

print("="*80)
print("ADD ID SAMPLE VALUES")
print("="*80)
for col in id_cols_add:
    if col in df_add.columns:
        print(f"\n{col}")
        print(df_add[col].dropna().astype(str).head(20).tolist())

================================================================================
CRG ID SAMPLE VALUES
================================================================================

student_id
['10000.111', '10000.111', '10000.111', '10000.111', '10000.111', '10000.111', '10000.111', '10000.111', '10000.111', '10000.111', '10000.111', '10000.111', '10000.111', '10000.111', '10000.111', '10000.111', '10000.111', '10000.111', '10000.111', '10000.111']

degree_id
['3.111', '3.111', '3.111', '3.111', '3.111', '3.111', '3.111', '3.111', '3.111', '3.111', '3.111', '3.111', '3.111', '3.111', '3.111', '3.111', '3.111', '3.111', '3.111', '3.111']

part_id
['20152', '20153', '20171', '20152', '20151', '20161', '20153', '20171', '20173', '20182', '20171', '20183', '20171', '20173', '20181', '20183', '20151', '20152', '20162', '20161']

course_id
['1016.111', '1017.111', '1019.111', '431.111', '432.111', '433.111', '434.111', '435.111', '436.111', '437.111', '438.111', '443.111', '451.111', '466.111', '466.111', '467.111', '501.111', '502.111', '503.111', '504.111']

student_course_id
['939272.111', '953865.111', '1076397.111', '925010.111', '901340.111', '973921.111', '949219.111', '1076396.111', '1131540.111', '1192637.111', '1076398.111', '1227299.111', '1076557.111', '1129422.111', '1168332.111', '1227298.111', '901338.111', '925007.111', '1012727.111', '982594.111']
================================================================================
ADD ID SAMPLE VALUES
================================================================================

student_id
['48.111', '48.111', '48.111', '128.111', '128.111', '128.111', '128.111', '128.111', '128.111', '128.111', '128.111', '128.111', '128.111', '129.111', '129.111', '129.111', '129.111', '129.111', '129.111', '129.111']

degree_id
['22.111', '22.111', '22.111', '19.111', '19.111', '19.111', '19.111', '19.111', '19.111', '19.111', '19.111', '19.111', '19.111', '19.111', '19.111', '19.111', '19.111', '19.111', '19.111', '19.111']

part_id
['20203', '20211', '20212', '20111', '20112', '20121', '20122', '20131', '20132', '20133', '20141', '20142', '20151', '20111', '20112', '20121', '20122', '20131', '20132', '20133']

student_status_id
['297550.111', '314343.111', '320948.111', '114381.111', '114382.111', '213711.111', '144893.111', '114383.111', '203128.111', '113733.111', '113734.111', '214969.111', '202549.111', '113735.111', '113736.111', '113737.111', '113738.111', '150498.111', '150499.111', '150500.111']

In [13]:
JOIN_KEYS = ["student_id", "degree_id", "part_id"]

print("="*80)
print("ADD UNIQUENESS CHECK")
print("="*80)

print("ADD rows:", len(df_add))
print("ADD unique JOIN_KEYS:", df_add[JOIN_KEYS].drop_duplicates().shape[0])

add_dup_mask = df_add.duplicated(JOIN_KEYS, keep=False)

print("ADD duplicated rows on JOIN_KEYS:", add_dup_mask.sum())
print("ADD duplicated groups on JOIN_KEYS:", df_add.loc[add_dup_mask, JOIN_KEYS].drop_duplicates().shape[0])

display(
    df_add.loc[
        add_dup_mask,
        JOIN_KEYS + [
            "student_status_id",
            "grade_version_id",
            "finish_status",
            "start_part_id",
            "finish_part_id",
            "start_agpa_points",
            "start_agpa_percent",
            "gpa_points",
            "gpa_percent",
            "end_agpa_points",
            "end_agpa_percent",
            "reg_total_semesters",
            "start_level_id",
            "start_level_name_pl",
        ]
    ]
    .sort_values(JOIN_KEYS)
    .head(100)
)

================================================================================
ADD UNIQUENESS CHECK
================================================================================
ADD rows: 179844
ADD unique JOIN_KEYS: 179844
ADD duplicated rows on JOIN_KEYS: 0
ADD duplicated groups on JOIN_KEYS: 0

Empty DataFrame
Columns: [student_id, degree_id, part_id, student_status_id, grade_version_id, finish_status, start_part_id, finish_part_id, start_agpa_points, start_agpa_percent, gpa_points, gpa_percent, end_agpa_points, end_agpa_percent, reg_total_semesters, start_level_id, start_level_name_pl]
Index: []

In [14]:
CRG_GRAIN = ["student_id", "degree_id", "part_id", "course_id"]

print("="*80)
print("CRG COURSE GRAIN CHECK")
print("="*80)

print("CRG rows:", len(df_crg))
print("CRG unique student_course_id:", df_crg["student_course_id"].nunique(dropna=False))
print("CRG duplicated student_course_id rows:", df_crg.duplicated(["student_course_id"], keep=False).sum())

print("CRG unique CRG_GRAIN:", df_crg[CRG_GRAIN].drop_duplicates().shape[0])

crg_dup_mask = df_crg.duplicated(CRG_GRAIN, keep=False)

print("CRG duplicated rows on student-degree-part-course:", crg_dup_mask.sum())
print("CRG duplicated groups:", df_crg.loc[crg_dup_mask, CRG_GRAIN].drop_duplicates().shape[0])

display(
    df_crg.loc[
        crg_dup_mask,
        CRG_GRAIN + [
            "student_course_id",
            "grade_id",
            "final_mark",
            "points",
            "finish_status",
            "course_outcome_status",
            "register_status",
            "attempt_number",
            "attempt_count",
        ]
    ]
    .sort_values(CRG_GRAIN)
    .head(100)
)

================================================================================
CRG COURSE GRAIN CHECK
================================================================================
CRG rows: 761347
CRG unique student_course_id: 761347
CRG duplicated student_course_id rows: 0
CRG unique CRG_GRAIN: 761347
CRG duplicated rows on student-degree-part-course: 0
CRG duplicated groups: 0

Empty DataFrame
Columns: [student_id, degree_id, part_id, course_id, student_course_id, grade_id, final_mark, points, finish_status, course_outcome_status, register_status, attempt_number, attempt_count]
Index: []

In [15]:
JOIN_KEYS = ["student_id", "degree_id", "part_id"]

add_snapshot_cols = [
    "student_status_id",
    "student_id",
    "degree_id",
    "part_id",

    # safe / start-of-semester features
    "start_agpa_points",
    "start_agpa_percent",
    "reg_total_semesters",
    "start_level_id",
    "start_level_name_pl",
    "start_part_id",

    # keep for audit only, not model input yet
    "finish_part_id",
    "finish_status",
]

df_add_snapshot = df_add[add_snapshot_cols].copy()

print("="*80)
print("PRE-MERGE VALIDATION")
print("="*80)

print("CRG rows before merge:", len(df_crg))
print("ADD snapshot rows:", len(df_add_snapshot))
print("ADD unique JOIN_KEYS:", df_add_snapshot[JOIN_KEYS].drop_duplicates().shape[0])

assert df_add_snapshot.duplicated(JOIN_KEYS).sum() == 0, "ADD is not unique on JOIN_KEYS."

df_merge_test = df_crg.merge(
    df_add_snapshot,
    on=JOIN_KEYS,
    how="left",
    validate="many_to_one",
    indicator=True,
    suffixes=("_crg", "_add")
)

print("\nRows after merge:", len(df_merge_test))
print("Row count changed:", len(df_merge_test) - len(df_crg))

assert len(df_merge_test) == len(df_crg), "Row count changed after merge. Investigate duplicate ADD keys."

print("\nMerge result:")
print(df_merge_test["_merge"].value_counts(dropna=False))

missing_snapshot_mask = df_merge_test["_merge"].eq("left_only")

print("\nMissing ADD snapshot rows:", missing_snapshot_mask.sum())
print("Missing ADD snapshot ratio:", missing_snapshot_mask.mean())

unmatched_snapshot_report = df_merge_test.loc[missing_snapshot_mask].copy()

print("\nUnmatched rows by part_id:")
display(unmatched_snapshot_report["part_id"].value_counts(dropna=False).head(30))

print("\nUnmatched rows by degree_id:")
display(unmatched_snapshot_report["degree_id"].value_counts(dropna=False).head(30))

print("\nUnmatched rows by register_status:")
display(unmatched_snapshot_report["register_status"].value_counts(dropna=False))

print("\nUnmatched rows by CRG finish_status:")
display(unmatched_snapshot_report["finish_status_crg"].value_counts(dropna=False))

print("\nUnmatched sample:")
display(
    unmatched_snapshot_report[
        [
            "student_course_id",
            "student_id",
            "degree_id",
            "part_id",
            "course_id",
            "grade_id",
            "final_mark",
            "points",
            "finish_status_crg",
            "register_status",
        ]
    ].head(100)
)

================================================================================
PRE-MERGE VALIDATION
================================================================================
CRG rows before merge: 761347
ADD snapshot rows: 179844
ADD unique JOIN_KEYS: 179844

Rows after merge: 761347
Row count changed: 0

Merge result:
_merge
both          761346
left_only          1
right_only         0
Name: count, dtype: int64

Missing ADD snapshot rows: 1
Missing ADD snapshot ratio: 1.313461535935651e-06

Unmatched rows by part_id:

part_id
20192    1
Name: count, dtype: Int64

Unmatched rows by degree_id:

degree_id
2.111    1
Name: count, dtype: int64[pyarrow]

Unmatched rows by register_status:

register_status
R    1
E    0
Name: count, dtype: int64

Unmatched rows by CRG finish_status:

finish_status_crg
P     1
F     0
FA    0
FE    0
Name: count, dtype: int64

Unmatched sample:

,student_course_id,student_id,degree_id,part_id,course_id,grade_id,final_mark,points,finish_status_crg,register_status
604532,1299845.111,3679.111,2.111,20192,710.111,977.111,86,3.25,P,R