In [ ]:
import pandas as pd

from src.paths import RAW_DIR

pd.set_option('display.max_columns', 50)
raw_path = RAW_DIR / "v_add_student_degree_status.parquet"

In [12]:
df_v_add_student_degree_status = pd.read_parquet(raw_path)

In [13]:
### drop request_id 
df_v_add_student_degree_status.head()

,student_status_id,student_id,request_id,part_id,degree_id,study_mode,gpa_percent,gpa_points,start_part_id,finish_part_id,start_agpa_percent,start_agpa_points,end_agpa_percent,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,finish_status,version_title_sl,start_level_id,start_level_name_pl
0,340275.111,28401.111,570675.111,20222.0,1.111,C,84.25,3.16,20221.0,NaN,89.07,3.34,86.24,3.24,8.0,21.0,7.0,20.0,0.0,0.0,5.0,14.0,0.0,0.0,2.0,NaN,القرار رقم 230,595.111,First Year
1,334725.111,28401.111,550329.111,20221.0,1.111,C,89.07,3.34,20221.0,NaN,0.00,0.00,89.07,3.34,5.0,14.0,5.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,القرار رقم 230,595.111,First Year
2,353697.111,28401.111,618048.111,20231.0,1.111,C,85.28,3.15,20221.0,NaN,86.24,3.24,85.90,3.21,8.0,20.0,7.0,18.0,0.0,0.0,12.0,34.0,0.0,0.0,3.0,NaN,القرار رقم 230,596.111,Second Year
3,361412.111,28401.111,648593.111,20232.0,1.111,C,85.45,3.18,20221.0,NaN,85.90,3.21,85.78,3.20,9.0,20.0,9.0,20.0,0.0,0.0,19.0,52.0,0.0,0.0,4.0,NaN,القرار رقم 230,596.111,Second Year
4,374249.111,28401.111,702262.111,20241.0,1.111,C,88.41,3.31,20221.0,NaN,85.78,3.20,86.28,3.22,9.0,17.0,9.0,17.0,0.0,0.0,28.0,72.0,0.0,0.0,5.0,NaN,القرار رقم 230,597.111,Third year

In [14]:
df_v_add_student_degree_status.info()

<class 'pandas.DataFrame'>
RangeIndex: 154779 entries, 0 to 154778
Data columns (total 29 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   student_status_id      154779 non-null  float64
 1   student_id             154779 non-null  float64
 2   request_id             146661 non-null  float64
 3   part_id                154779 non-null  float64
 4   degree_id              152653 non-null  float64
 5   study_mode             154779 non-null  str
 6   gpa_percent            154768 non-null  float64
 7   gpa_points             154768 non-null  float64
 8   start_part_id          154774 non-null  float64
 9   finish_part_id         107879 non-null  float64
 10  start_agpa_percent     154768 non-null  float64
 11  start_agpa_points      154768 non-null  float64
 12  end_agpa_percent       154768 non-null  float64
 13  end_agpa_points        154768 non-null  float64
 14  semester_reg_courses   154768 non-null  float64
 15  semester_reg_credits   154768 non-null  float64
 16  semester_pass_courses  154768 non-null  float64
 17  semester_pass_credits  154768 non-null  float64
 18  semester_fail_courses  154768 non-null  float64
 19  semester_fail_credits  154768 non-null  float64
 20  total_pass_courses     154768 non-null  float64
 21  total_pass_credits     154768 non-null  float64
 22  total_fail_courses     154768 non-null  float64
 23  total_fail_credits     154768 non-null  float64
 24  reg_total_semesters    154162 non-null  float64
 25  finish_status          108171 non-null  str
 26  version_title_sl       154768 non-null  str
 27  start_level_id         152660 non-null  float64
 28  start_level_name_pl    154779 non-null  str
dtypes: float64(25), str(4)
memory usage: 40.4 MB

In [16]:
df=df_v_add_student_degree_status.copy()

In [19]:
df[df['degree_id'].isnull()].head(20)

,student_status_id,student_id,request_id,part_id,degree_id,study_mode,gpa_percent,gpa_points,start_part_id,finish_part_id,start_agpa_percent,start_agpa_points,end_agpa_percent,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,finish_status,version_title_sl,start_level_id,start_level_name_pl
407,334317.111,28016.111,NaN,20221.0,NaN,C,NaN,NaN,20221.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,First Year
29277,303732.111,20012.111,339881.111,20211.0,NaN,C,0.0,0.0,20211.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,القرار رقم 230,NaN,First Year
29337,303743.111,20023.111,339894.111,20211.0,NaN,C,0.0,0.0,20211.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,القرار رقم 230,NaN,First Year
31771,305145.111,21371.111,341301.111,20211.0,NaN,C,0.0,0.0,20211.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,القرار رقم 230,NaN,First Year
31772,305149.111,21375.111,341305.111,20211.0,NaN,C,0.0,0.0,20211.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,القرار رقم 230,NaN,First Year
31773,305154.111,21380.111,341310.111,20211.0,NaN,C,0.0,0.0,20211.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,القرار رقم 230,NaN,First Year
31774,302228.111,18529.111,338297.111,20211.0,NaN,C,0.0,0.0,20211.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,القرار رقم 230,NaN,First Year
31787,302243.111,18544.111,338312.111,20211.0,NaN,C,0.0,0.0,20211.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,القرار رقم 230,NaN,First Year
31801,302248.111,18549.111,338317.111,20211.0,NaN,C,0.0,0.0,20211.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,القرار رقم 230,NaN,First Year
31802,302257.111,18558.111,338326.111,20211.0,NaN,C,0.0,0.0,20211.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,القرار رقم 230,NaN,First Year
31803,302258.111,18559.111,338327.111,20211.0,NaN,C,0.0,0.0,20211.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,القرار رقم 230,NaN,First Year
31804,302260.111,18561.111,338329.111,20211.0,NaN,C,0.0,0.0,20211.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,القرار رقم 230,NaN,First Year
31805,302261.111,18562.111,338330.111,20211.0,NaN,C,0.0,0.0,20211.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,القرار رقم 230,NaN,First Year
31806,303554.111,19836.111,339682.111,20211.0,NaN,C,0.0,0.0,20211.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,القرار رقم 230,NaN,First Year
31817,303565.111,19847.111,339693.111,20211.0,NaN,C,0.0,0.0,20211.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,القرار رقم 230,NaN,First Year
31858,303583.111,19865.111,339715.111,20211.0,NaN,C,0.0,0.0,20211.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,القرار رقم 230,NaN,First Year
31859,303584.111,19866.111,339718.111,20211.0,NaN,C,0.0,0.0,20211.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,القرار رقم 230,NaN,First Year
31860,303585.111,19867.111,339719.111,20211.0,NaN,C,0.0,0.0,20211.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,القرار رقم 230,NaN,First Year
32001,304720.111,20957.111,340886.111,20211.0,NaN,C,0.0,0.0,20211.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,القرار رقم 230,NaN,First Year
32002,304722.111,20959.111,340888.111,20211.0,NaN,C,0.0,0.0,20211.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,القرار رقم 230,NaN,First Year

In [20]:
df[df['finish_status'].isnull()].head(20)

,student_status_id,student_id,request_id,part_id,degree_id,study_mode,gpa_percent,gpa_points,start_part_id,finish_part_id,start_agpa_percent,start_agpa_points,end_agpa_percent,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,finish_status,version_title_sl,start_level_id,start_level_name_pl
0,340275.111,28401.111,570675.111,20222.0,1.111,C,84.25,3.16,20221.0,NaN,89.07,3.34,86.24,3.24,8.0,21.0,7.0,20.0,0.0,0.0,5.0,14.0,0.0,0.0,2.0,NaN,القرار رقم 230,595.111,First Year
1,334725.111,28401.111,550329.111,20221.0,1.111,C,89.07,3.34,20221.0,NaN,0.00,0.00,89.07,3.34,5.0,14.0,5.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,القرار رقم 230,595.111,First Year
2,353697.111,28401.111,618048.111,20231.0,1.111,C,85.28,3.15,20221.0,NaN,86.24,3.24,85.90,3.21,8.0,20.0,7.0,18.0,0.0,0.0,12.0,34.0,0.0,0.0,3.0,NaN,القرار رقم 230,596.111,Second Year
3,361412.111,28401.111,648593.111,20232.0,1.111,C,85.45,3.18,20221.0,NaN,85.90,3.21,85.78,3.20,9.0,20.0,9.0,20.0,0.0,0.0,19.0,52.0,0.0,0.0,4.0,NaN,القرار رقم 230,596.111,Second Year
4,374249.111,28401.111,702262.111,20241.0,1.111,C,88.41,3.31,20221.0,NaN,85.78,3.20,86.28,3.22,9.0,17.0,9.0,17.0,0.0,0.0,28.0,72.0,0.0,0.0,5.0,NaN,القرار رقم 230,597.111,Third year
5,383138.111,28401.111,738918.111,20242.0,1.111,C,86.45,3.19,20221.0,NaN,86.28,3.22,86.31,3.21,7.0,20.0,7.0,20.0,0.0,0.0,37.0,89.0,0.0,0.0,6.0,NaN,القرار رقم 230,597.111,Third year
6,390813.111,28401.111,773040.111,20243.0,1.111,C,85.33,3.17,20221.0,NaN,86.31,3.21,86.26,3.21,3.0,6.0,3.0,6.0,0.0,0.0,44.0,109.0,0.0,0.0,7.0,NaN,القرار رقم 230,598.111,Fourth Year
7,396076.111,28401.111,807826.111,20251.0,1.111,C,0.00,0.00,20221.0,NaN,86.26,3.21,86.26,3.21,8.0,18.0,0.0,0.0,0.0,0.0,47.0,115.0,0.0,0.0,8.0,NaN,القرار رقم 230,598.111,Fourth Year
8,341773.111,28404.111,575872.111,20222.0,24.111,C,55.33,1.25,20221.0,NaN,67.72,2.06,63.59,1.79,4.0,12.0,2.0,6.0,1.0,3.0,5.0,15.0,1.0,3.0,2.0,NaN,القرار رقم 230,674.111,Second Year
9,353768.111,28404.111,618193.111,20231.0,24.111,C,61.81,1.83,20221.0,NaN,63.59,1.79,66.97,2.13,5.0,16.0,4.0,13.0,1.0,3.0,7.0,21.0,2.0,6.0,3.0,NaN,القرار رقم 230,674.111,Second Year
10,334728.111,28404.111,551268.111,20221.0,24.111,C,67.72,2.06,20221.0,NaN,0.00,0.00,67.72,2.06,6.0,18.0,5.0,15.0,1.0,3.0,0.0,0.0,0.0,0.0,1.0,NaN,القرار رقم 230,674.111,Second Year
11,364325.111,28404.111,652882.111,20232.0,24.111,C,71.35,2.51,20221.0,NaN,66.97,2.13,70.02,2.40,6.0,17.0,6.0,17.0,0.0,0.0,11.0,34.0,3.0,9.0,4.0,NaN,القرار رقم 230,674.111,Second Year
12,374021.111,28404.111,701878.111,20241.0,24.111,C,58.94,1.44,20221.0,NaN,69.60,2.37,67.04,2.15,6.0,18.0,4.0,11.0,2.0,7.0,20.0,60.0,3.0,9.0,6.0,NaN,القرار رقم 230,675.111,Third year
13,387839.111,28404.111,758097.111,20242.0,24.111,C,62.63,1.84,20221.0,NaN,67.04,2.15,68.18,2.27,5.0,16.0,4.0,13.0,1.0,3.0,24.0,71.0,5.0,16.0,7.0,NaN,القرار رقم 230,675.111,Third year
14,369340.111,28404.111,681470.111,20233.0,24.111,C,67.33,2.25,20221.0,NaN,70.02,2.40,69.60,2.37,3.0,9.0,3.0,9.0,0.0,0.0,17.0,51.0,3.0,9.0,5.0,NaN,القرار رقم 230,675.111,Third year
15,395749.111,28404.111,804180.111,20251.0,24.111,C,0.00,0.00,20221.0,NaN,68.18,2.27,68.18,2.27,5.0,15.0,0.0,0.0,0.0,0.0,28.0,84.0,6.0,19.0,8.0,NaN,القرار رقم 230,676.111,Fourth Year
17,343461.111,28407.111,581620.111,20222.0,2.111,C,78.35,2.82,20221.0,NaN,65.50,1.58,73.03,2.31,5.0,17.0,5.0,17.0,0.0,0.0,2.0,6.0,2.0,6.0,2.0,NaN,القرار رقم 230,583.111,Second Year
18,334731.111,28407.111,550230.111,20221.0,2.111,C,65.50,1.58,20221.0,NaN,0.00,0.00,65.50,1.58,4.0,12.0,2.0,6.0,2.0,6.0,0.0,0.0,0.0,0.0,1.0,NaN,القرار رقم 230,583.111,Second Year
19,352899.111,28407.111,616507.111,20231.0,2.111,C,74.83,2.64,20221.0,NaN,73.46,2.38,75.75,2.65,8.0,24.0,8.0,24.0,0.0,0.0,9.0,31.0,2.0,6.0,4.0,NaN,القرار رقم 230,584.111,Third year
20,348785.111,28407.111,602212.111,20223.0,2.111,C,75.00,2.63,20221.0,NaN,73.03,2.31,73.46,2.38,2.0,8.0,2.0,8.0,0.0,0.0,7.0,23.0,2.0,6.0,3.0,NaN,القرار رقم 230,584.111,Third year

In [ ]:
df[df['finish_part_id'].isnull()].head(20)

,student_status_id,student_id,request_id,part_id,degree_id,study_mode,gpa_percent,gpa_points,start_part_id,finish_part_id,start_agpa_percent,start_agpa_points,end_agpa_percent,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,finish_status,version_title_sl,start_level_id,start_level_name_pl
0,340275.111,28401.111,570675.111,20222.0,1.111,C,84.25,3.16,20221.0,NaN,89.07,3.34,86.24,3.24,8.0,21.0,7.0,20.0,0.0,0.0,5.0,14.0,0.0,0.0,2.0,NaN,القرار رقم 230,595.111,First Year
1,334725.111,28401.111,550329.111,20221.0,1.111,C,89.07,3.34,20221.0,NaN,0.00,0.00,89.07,3.34,5.0,14.0,5.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,القرار رقم 230,595.111,First Year
2,353697.111,28401.111,618048.111,20231.0,1.111,C,85.28,3.15,20221.0,NaN,86.24,3.24,85.90,3.21,8.0,20.0,7.0,18.0,0.0,0.0,12.0,34.0,0.0,0.0,3.0,NaN,القرار رقم 230,596.111,Second Year
3,361412.111,28401.111,648593.111,20232.0,1.111,C,85.45,3.18,20221.0,NaN,85.90,3.21,85.78,3.20,9.0,20.0,9.0,20.0,0.0,0.0,19.0,52.0,0.0,0.0,4.0,NaN,القرار رقم 230,596.111,Second Year
4,374249.111,28401.111,702262.111,20241.0,1.111,C,88.41,3.31,20221.0,NaN,85.78,3.20,86.28,3.22,9.0,17.0,9.0,17.0,0.0,0.0,28.0,72.0,0.0,0.0,5.0,NaN,القرار رقم 230,597.111,Third year
5,383138.111,28401.111,738918.111,20242.0,1.111,C,86.45,3.19,20221.0,NaN,86.28,3.22,86.31,3.21,7.0,20.0,7.0,20.0,0.0,0.0,37.0,89.0,0.0,0.0,6.0,NaN,القرار رقم 230,597.111,Third year
6,390813.111,28401.111,773040.111,20243.0,1.111,C,85.33,3.17,20221.0,NaN,86.31,3.21,86.26,3.21,3.0,6.0,3.0,6.0,0.0,0.0,44.0,109.0,0.0,0.0,7.0,NaN,القرار رقم 230,598.111,Fourth Year
7,396076.111,28401.111,807826.111,20251.0,1.111,C,0.00,0.00,20221.0,NaN,86.26,3.21,86.26,3.21,8.0,18.0,0.0,0.0,0.0,0.0,47.0,115.0,0.0,0.0,8.0,NaN,القرار رقم 230,598.111,Fourth Year
8,341773.111,28404.111,575872.111,20222.0,24.111,C,55.33,1.25,20221.0,NaN,67.72,2.06,63.59,1.79,4.0,12.0,2.0,6.0,1.0,3.0,5.0,15.0,1.0,3.0,2.0,NaN,القرار رقم 230,674.111,Second Year
9,353768.111,28404.111,618193.111,20231.0,24.111,C,61.81,1.83,20221.0,NaN,63.59,1.79,66.97,2.13,5.0,16.0,4.0,13.0,1.0,3.0,7.0,21.0,2.0,6.0,3.0,NaN,القرار رقم 230,674.111,Second Year
10,334728.111,28404.111,551268.111,20221.0,24.111,C,67.72,2.06,20221.0,NaN,0.00,0.00,67.72,2.06,6.0,18.0,5.0,15.0,1.0,3.0,0.0,0.0,0.0,0.0,1.0,NaN,القرار رقم 230,674.111,Second Year
11,364325.111,28404.111,652882.111,20232.0,24.111,C,71.35,2.51,20221.0,NaN,66.97,2.13,70.02,2.40,6.0,17.0,6.0,17.0,0.0,0.0,11.0,34.0,3.0,9.0,4.0,NaN,القرار رقم 230,674.111,Second Year
12,374021.111,28404.111,701878.111,20241.0,24.111,C,58.94,1.44,20221.0,NaN,69.60,2.37,67.04,2.15,6.0,18.0,4.0,11.0,2.0,7.0,20.0,60.0,3.0,9.0,6.0,NaN,القرار رقم 230,675.111,Third year
13,387839.111,28404.111,758097.111,20242.0,24.111,C,62.63,1.84,20221.0,NaN,67.04,2.15,68.18,2.27,5.0,16.0,4.0,13.0,1.0,3.0,24.0,71.0,5.0,16.0,7.0,NaN,القرار رقم 230,675.111,Third year
14,369340.111,28404.111,681470.111,20233.0,24.111,C,67.33,2.25,20221.0,NaN,70.02,2.40,69.60,2.37,3.0,9.0,3.0,9.0,0.0,0.0,17.0,51.0,3.0,9.0,5.0,NaN,القرار رقم 230,675.111,Third year
15,395749.111,28404.111,804180.111,20251.0,24.111,C,0.00,0.00,20221.0,NaN,68.18,2.27,68.18,2.27,5.0,15.0,0.0,0.0,0.0,0.0,28.0,84.0,6.0,19.0,8.0,NaN,القرار رقم 230,676.111,Fourth Year
17,343461.111,28407.111,581620.111,20222.0,2.111,C,78.35,2.82,20221.0,NaN,65.50,1.58,73.03,2.31,5.0,17.0,5.0,17.0,0.0,0.0,2.0,6.0,2.0,6.0,2.0,NaN,القرار رقم 230,583.111,Second Year
18,334731.111,28407.111,550230.111,20221.0,2.111,C,65.50,1.58,20221.0,NaN,0.00,0.00,65.50,1.58,4.0,12.0,2.0,6.0,2.0,6.0,0.0,0.0,0.0,0.0,1.0,NaN,القرار رقم 230,583.111,Second Year
19,352899.111,28407.111,616507.111,20231.0,2.111,C,74.83,2.64,20221.0,NaN,73.46,2.38,75.75,2.65,8.0,24.0,8.0,24.0,0.0,0.0,9.0,31.0,2.0,6.0,4.0,NaN,القرار رقم 230,584.111,Third year
20,348785.111,28407.111,602212.111,20223.0,2.111,C,75.00,2.63,20221.0,NaN,73.03,2.31,73.46,2.38,2.0,8.0,2.0,8.0,0.0,0.0,7.0,23.0,2.0,6.0,3.0,NaN,القرار رقم 230,584.111,Third year

In [25]:
id_cols_to_check = [
    "student_status_id",
    "student_id",
    "part_id",
    "degree_id",
    "start_part_id",
    "finish_part_id",
    "start_level_id",
]

for col in id_cols_to_check:
    if col in df.columns:
        s = df[col].dropna().astype(str)

        # الجزء بعد النقطة
        suffix = s.str.extract(r"\.(.*)$")[0]

        print("\nCOLUMN:", col)
        print("non-null:", df[col].notna().sum())
        print("null:", df[col].isna().sum())
        print("sample values:")
        print(df[col].dropna().head(10).tolist())
        print("top suffixes:")
        print(suffix.value_counts(dropna=False).head(10))

COLUMN: student_status_id
non-null: 154779
null: 0
sample values:
[340275.111, 334725.111, 353697.111, 361412.111, 374249.111, 383138.111, 390813.111, 396076.111, 341773.111, 353768.111]
top suffixes:
0
111    154776
101         3
Name: count, dtype: int64

COLUMN: student_id
non-null: 154779
null: 0
sample values:
[28401.111, 28401.111, 28401.111, 28401.111, 28401.111, 28401.111, 28401.111, 28401.111, 28404.111, 28404.111]
top suffixes:
0
111    154779
Name: count, dtype: int64

COLUMN: part_id
non-null: 154779
null: 0
sample values:
[20222.0, 20221.0, 20231.0, 20232.0, 20241.0, 20242.0, 20243.0, 20251.0, 20222.0, 20231.0]
top suffixes:
0
0    154779
Name: count, dtype: int64

COLUMN: degree_id
non-null: 152653
null: 2126
sample values:
[1.111, 1.111, 1.111, 1.111, 1.111, 1.111, 1.111, 1.111, 24.111, 24.111]
top suffixes:
0
111    152653
Name: count, dtype: int64

COLUMN: start_part_id
non-null: 154774
null: 5
sample values:
[20221.0, 20221.0, 20221.0, 20221.0, 20221.0, 20221.0, 20221.0, 20221.0, 20221.0, 20221.0]
top suffixes:
0
0    154774
Name: count, dtype: int64

COLUMN: finish_part_id
non-null: 107879
null: 46900
sample values:
[20221.0, 20222.0, 20222.0, 20221.0, 20231.0, 20231.0, 20231.0, 20242.0, 20242.0, 20242.0]
top suffixes:
0
0    107879
Name: count, dtype: int64

COLUMN: start_level_id
non-null: 152660
null: 2119
sample values:
[595.111, 595.111, 596.111, 596.111, 597.111, 597.111, 598.111, 598.111, 674.111, 674.111]
top suffixes:
0
111    152660
Name: count, dtype: int64

In [26]:
course_count_cols = [
    "semester_reg_courses",
    "semester_pass_courses",
    "semester_fail_courses",
    "total_pass_courses",
    "total_fail_courses",
    "reg_total_semesters",
]

for col in course_count_cols:
    if col in df.columns:
        s = pd.to_numeric(df[col], errors="coerce")
        non_null = s.dropna()
        fractional = non_null[non_null % 1 != 0]

        print("\nCOLUMN:", col)
        print("non-null:", non_null.shape[0])
        print("null:", s.isna().sum())
        print("fractional count:", fractional.shape[0])
        if fractional.shape[0] > 0:
            print("fractional examples:", fractional.head(10).tolist())

COLUMN: semester_reg_courses
non-null: 154768
null: 11
fractional count: 0

COLUMN: semester_pass_courses
non-null: 154768
null: 11
fractional count: 0

COLUMN: semester_fail_courses
non-null: 154768
null: 11
fractional count: 0

COLUMN: total_pass_courses
non-null: 154768
null: 11
fractional count: 0

COLUMN: total_fail_courses
non-null: 154768
null: 11
fractional count: 0

COLUMN: reg_total_semesters
non-null: 154162
null: 617
fractional count: 0

In [27]:
print("Rows:", len(df))
print("Unique student_status_id:", df["student_status_id"].nunique(dropna=True))
print("Duplicated student_status_id rows:", df.duplicated(subset=["student_status_id"], keep=False).sum())

display(
    df[df.duplicated(subset=["student_status_id"], keep=False)]
    .sort_values("student_status_id")
    .head(20)
)

Rows: 154779
Unique student_status_id: 154779
Duplicated student_status_id rows: 0

Empty DataFrame
Columns: [student_status_id, student_id, request_id, part_id, degree_id, study_mode, gpa_percent, gpa_points, start_part_id, finish_part_id, start_agpa_percent, start_agpa_points, end_agpa_percent, end_agpa_points, semester_reg_courses, semester_reg_credits, semester_pass_courses, semester_pass_credits, semester_fail_courses, semester_fail_credits, total_pass_courses, total_pass_credits, total_fail_courses, total_fail_credits, reg_total_semesters, finish_status, version_title_sl, start_level_id, start_level_name_pl]
Index: []

In [28]:
gpa_agpa_cols = [
    "gpa_percent",
    "gpa_points",
    "start_agpa_percent",
    "start_agpa_points",
    "end_agpa_percent",
    "end_agpa_points",
]

missing_gpa_agpa_rows = df[df[gpa_agpa_cols].isna().any(axis=1)]

print("Rows with missing GPA/AGPA:", len(missing_gpa_agpa_rows))

display(
    missing_gpa_agpa_rows[
        [
            "student_status_id",
            "student_id",
            "part_id",
            "degree_id",
            "study_mode",
            "gpa_percent",
            "gpa_points",
            "start_agpa_percent",
            "start_agpa_points",
            "end_agpa_percent",
            "end_agpa_points",
            "semester_reg_courses",
            "semester_reg_credits",
            "version_title_sl",
        ]
    ]
)

Rows with missing GPA/AGPA: 11

,student_status_id,student_id,part_id,degree_id,study_mode,gpa_percent,gpa_points,start_agpa_percent,start_agpa_points,end_agpa_percent,end_agpa_points,semester_reg_courses,semester_reg_credits,version_title_sl
407,334317.111,28016.111,20221.0,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132937,334382.111,28081.111,20221.0,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142910,334572.111,28271.111,20221.0,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142966,334580.111,28279.111,20221.0,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142985,334584.111,28283.111,20221.0,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143175,334508.111,28207.111,20221.0,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143267,334492.111,28191.111,20221.0,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143268,334493.111,28192.111,20221.0,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143804,334561.111,28260.111,20221.0,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143894,334515.111,28214.111,20221.0,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150496,334415.111,28114.111,20221.0,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
df[df['reg_total_semesters'].isnull()]

,student_status_id,student_id,request_id,part_id,degree_id,study_mode,gpa_percent,gpa_points,start_part_id,finish_part_id,start_agpa_percent,start_agpa_points,end_agpa_percent,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,finish_status,version_title_sl,start_level_id,start_level_name_pl
407,334317.111,28016.111,NaN,20221.0,NaN,C,NaN,NaN,20221.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,First Year
3569,187712.111,1909.111,52245.111,20112.0,13.111,C,60.67,1.89,20111.0,20162.0,59.67,1.70,60.21,1.80,7.0,18.0,7.0,18.0,0.0,0.0,5.0,12.0,1.0,3.0,NaN,GRADUATED,القرار الوزاري الموحد,29.111,First Year
3570,117943.111,1909.111,52244.111,20111.0,13.111,C,59.67,1.70,20111.0,20162.0,0.00,0.00,59.67,1.70,6.0,15.0,5.0,12.0,1.0,3.0,0.0,0.0,0.0,0.0,NaN,GRADUATED,القرار الوزاري الموحد,29.111,First Year
3571,162367.111,1909.111,52248.111,20122.0,13.111,C,61.44,1.97,20111.0,20162.0,59.48,1.68,59.95,1.75,7.0,17.0,6.0,15.0,1.0,2.0,17.0,44.0,4.0,11.0,NaN,GRADUATED,القرار الوزاري الموحد,30.111,Second Year
3572,187713.111,1909.111,52246.111,20113.0,13.111,C,46.00,0.00,20111.0,20162.0,60.21,1.80,60.48,1.80,1.0,3.0,0.0,0.0,1.0,3.0,13.0,32.0,1.0,3.0,NaN,GRADUATED,القرار الوزاري الموحد,30.111,Second Year
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151854,187288.111,1862.111,51644.111,20142.0,13.111,C,77.28,2.76,20111.0,20162.0,71.90,2.51,72.59,2.54,7.0,18.0,7.0,18.0,0.0,0.0,45.0,125.0,1.0,1.0,NaN,GRADUATED,القرار الوزاري الموحد,32.111,Fourth Year
151855,187289.111,1862.111,51645.111,20151.0,13.111,C,74.24,2.46,20111.0,20162.0,72.59,2.54,72.77,2.53,8.0,17.0,6.0,14.0,2.0,3.0,52.0,143.0,1.0,1.0,NaN,GRADUATED,القرار الوزاري الموحد,33.111,Fifth year
151856,149315.111,1862.111,51646.111,20152.0,13.111,C,66.33,2.23,20111.0,20162.0,72.77,2.53,72.28,2.51,10.0,21.0,10.0,21.0,0.0,0.0,58.0,157.0,3.0,4.0,NaN,GRADUATED,القرار الوزاري الموحد,33.111,Fifth year
151857,149316.111,1862.111,51647.111,20161.0,13.111,C,60.00,2.00,20111.0,20162.0,72.28,2.51,72.43,2.53,1.0,2.0,1.0,2.0,0.0,0.0,68.0,178.0,3.0,4.0,NaN,GRADUATED,القرار الوزاري الموحد,33.111,Fifth year
151858,232365.111,1862.111,NaN,20162.0,13.111,C,0.00,0.00,20111.0,20162.0,72.43,2.53,72.43,2.53,0.0,0.0,0.0,0.0,0.0,0.0,69.0,180.0,3.0,4.0,NaN,GRADUATED,القرار الوزاري الموحد,33.111,Fifth year

In [ ]:
df_v_add_student_degree_status.isna().sum()

student_status_id            0
student_id                   0
request_id                8107
part_id                      0
degree_id                 2115
study_mode                   0
gpa_percent                  0
gpa_points                   0
start_part_id                5
finish_part_id           46889
start_agpa_percent           0
start_agpa_points            0
end_agpa_percent             0
end_agpa_points              0
semester_reg_courses         0
semester_reg_credits         0
semester_pass_courses        0
semester_pass_credits        0
semester_fail_courses        0
semester_fail_credits        0
total_pass_courses           0
total_pass_credits           0
total_fail_courses           0
total_fail_credits           0
reg_total_semesters        606
finish_status            46597
version_title_sl             0
start_level_id            2108
start_level_name_pl          0
dtype: int64

In [ ]:
df_v_add_student_degree_status['finish_status'].value_counts()

finish_status
GRADUATED                  87832
CLOSE_FILE                 13275
WITHDRAWN                   3559
CHANGE_PLAN                 1885
CANCEL_ADMISSION             588
FINAL_DISMISS                516
CHANGE_DEGREE                287
CHANGE_FACULTY               225
COMPARISON_UNDERAPPLIED        4
Name: count, dtype: int64

In [ ]:
df_v_add_student_degree_status[df_v_add_student_degree_status['finish_status'].eq("GRADUATED")]

,student_status_id,student_id,request_id,part_id,degree_id,study_mode,gpa_percent,gpa_points,start_part_id,finish_part_id,start_agpa_percent,start_agpa_points,end_agpa_percent,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,finish_status,version_title_sl,start_level_id,start_level_name_pl
960,155347.111,10000.111,36525.111,20151.0,3.111,C,68.20,2.41,20151.0,20191.0,0.00,0.00,68.20,2.41,6.0,17.0,6.0,17.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,GRADUATED,القرار رقم 230,205.111,First Year
961,155348.111,10000.111,36526.111,20152.0,3.111,C,67.20,2.36,20151.0,20191.0,68.20,2.41,67.80,2.39,6.0,18.0,6.0,18.0,0.0,0.0,6.0,17.0,0.0,0.0,2.0,GRADUATED,القرار رقم 230,205.111,First Year
962,177896.111,10000.111,127746.111,20162.0,3.111,C,63.40,2.17,20151.0,20191.0,66.40,2.32,65.60,2.28,6.0,18.0,6.0,18.0,0.0,0.0,21.0,62.0,0.0,0.0,5.0,GRADUATED,القرار رقم 230,206.111,Second Year
963,155349.111,10000.111,36527.111,20153.0,3.111,C,65.00,2.25,20151.0,20191.0,67.80,2.39,67.20,2.36,3.0,9.0,3.0,9.0,0.0,0.0,12.0,35.0,0.0,0.0,3.0,GRADUATED,القرار رقم 230,206.111,Second Year
964,155350.111,10000.111,36528.111,20161.0,3.111,C,64.40,2.22,20151.0,20191.0,67.20,2.36,66.40,2.32,6.0,18.0,6.0,18.0,0.0,0.0,15.0,44.0,0.0,0.0,4.0,GRADUATED,القرار رقم 230,206.111,Second Year
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154744,318083.111,16029.111,498579.111,20212.0,11.111,C,61.18,1.93,20201.0,20242.0,65.49,1.99,66.27,2.22,7.0,17.0,7.0,17.0,0.0,0.0,17.0,38.0,4.0,11.0,5.0,GRADUATED,القرار رقم 230,706.111,Second Year
154745,352418.111,16029.111,615883.111,20231.0,11.111,C,65.76,1.94,20201.0,20242.0,69.65,2.38,69.01,2.31,6.0,17.0,4.0,13.0,2.0,4.0,37.0,93.0,4.0,11.0,9.0,GRADUATED,القرار رقم 230,707.111,Third year
154746,360874.111,16029.111,647914.111,20232.0,11.111,C,68.18,1.96,20201.0,20242.0,69.01,2.31,69.38,2.29,6.0,17.0,4.0,11.0,2.0,6.0,41.0,106.0,6.0,15.0,10.0,GRADUATED,القرار رقم 230,707.111,Third year
154747,380611.111,16029.111,734398.111,20242.0,11.111,C,72.00,2.60,20201.0,20242.0,66.80,2.34,68.00,2.40,4.0,12.0,4.0,12.0,0.0,0.0,49.0,129.0,9.0,23.0,12.0,GRADUATED,القرار رقم 230,708.111,Fourth Year
154748,373095.111,16029.111,697778.111,20241.0,11.111,C,62.00,1.59,20201.0,20242.0,69.38,2.29,69.99,2.34,6.0,17.0,4.0,12.0,1.0,2.0,45.0,117.0,8.0,21.0,11.0,GRADUATED,القرار رقم 230,708.111,Fourth Year