In [1]:
import pandas as pd 
# pd.set_option('display.max_columns', 100)
# pd.set_option('display.max_rows', 100)

In [2]:
df=pd.read_parquet(r"D:\AI\Real projects\Academic_Advisor\data\raw\v_acs_grade.parquet")
df.head(8)

,grade_id,grade_version_id,version_title_sl,version_number,from_percent,to_percent,points,from_semester_id,till_semester_id,finish_status,grade_show,active
0,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
1,673.111,2.111,القرار الوزاري الموحد,2,98.0,100.0,4.00,20111.0,20162.0,P,A+,A
2,999.111,1.111,تأسيس الجامعة,1,0.0,0.0,0.00,20051.0,20111.0,NaN,NaN,A
3,974.111,3.111,القرار رقم 230,230,98.0,100.0,4.00,20162.0,NaN,P,A+,A
4,674.111,2.111,القرار الوزاري الموحد,2,95.0,97.0,3.75,20111.0,20162.0,P,A,A
5,85.111,1.111,تأسيس الجامعة,1,90.0,100.0,4.00,20051.0,20111.0,P,A,A
6,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
7,975.111,3.111,القرار رقم 230,230,95.0,97.0,3.75,20162.0,NaN,P,A,A

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   grade_id          79 non-null     float64
 1   grade_version_id  108 non-null    float64
 2   version_title_sl  82 non-null     str
 3   version_number    82 non-null     str
 4   from_percent      77 non-null     float64
 5   to_percent        77 non-null     float64
 6   points            77 non-null     float64
 7   from_semester_id  82 non-null     float64
 8   till_semester_id  54 non-null     float64
 9   finish_status     73 non-null     str
 10  grade_show        70 non-null     str
 11  active            108 non-null    str
dtypes: float64(7), str(5)
memory usage: 13.1 KB

In [4]:
df['grade_id'].isna().sum()
df[df['grade_id'].isna()]

,grade_id,grade_version_id,version_title_sl,version_number,from_percent,to_percent,points,from_semester_id,till_semester_id,finish_status,grade_show,active
0,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
6,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
8,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
12,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
16,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
21,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
24,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
29,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
33,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
39,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
42,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
45,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
49,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
53,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
57,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
62,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
67,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
71,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
73,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
77,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
82,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
84,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
92,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
93,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
102,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
104,NaN,1.111,تأسيس الجامعة,1,NaN,NaN,NaN,20051.0,20111.0,NaN,NaN,A
105,NaN,2.111,القرار الوزاري الموحد,2,NaN,NaN,NaN,20111.0,20162.0,NaN,NaN,A
106,NaN,3.111,القرار رقم 230,230,NaN,NaN,NaN,20162.0,NaN,NaN,NaN,A
107,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A

In [5]:
df1=df.drop(df[df['grade_id'].isna()].index,)

In [6]:
df1

,grade_id,grade_version_id,version_title_sl,version_number,from_percent,to_percent,points,from_semester_id,till_semester_id,finish_status,grade_show,active
1,673.111,2.111,القرار الوزاري الموحد,2,98.0,100.0,4.00,20111.0,20162.0,P,A+,A
2,999.111,1.111,تأسيس الجامعة,1,0.0,0.0,0.00,20051.0,20111.0,NaN,NaN,A
3,974.111,3.111,القرار رقم 230,230,98.0,100.0,4.00,20162.0,NaN,P,A+,A
4,674.111,2.111,القرار الوزاري الموحد,2,95.0,97.0,3.75,20111.0,20162.0,P,A,A
5,85.111,1.111,تأسيس الجامعة,1,90.0,100.0,4.00,20051.0,20111.0,P,A,A
...,...,...,...,...,...,...,...,...,...,...,...,...
98,1006.111,2.111,القرار الوزاري الموحد,2,0.0,0.0,0.00,20111.0,20162.0,X,X,A
99,1006.111,2.111,القرار الوزاري الموحد,2,0.0,0.0,0.00,20111.0,20162.0,X,X,A
100,1005.111,3.111,القرار رقم 230,230,0.0,0.0,0.00,20162.0,NaN,L,L,A
101,1007.111,2.111,القرار الوزاري الموحد,2,0.0,0.0,0.00,20111.0,20162.0,L,L,A
103,1009.111,1.111,تأسيس الجامعة,1,0.0,0.0,0.00,20051.0,20111.0,L,L,A

In [7]:
df1.info()

<class 'pandas.DataFrame'>
Index: 79 entries, 1 to 103
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   grade_id          79 non-null     float64
 1   grade_version_id  79 non-null     float64
 2   version_title_sl  79 non-null     str
 3   version_number    79 non-null     str
 4   from_percent      77 non-null     float64
 5   to_percent        77 non-null     float64
 6   points            77 non-null     float64
 7   from_semester_id  79 non-null     float64
 8   till_semester_id  52 non-null     float64
 9   finish_status     73 non-null     str
 10  grade_show        70 non-null     str
 11  active            79 non-null     str
dtypes: float64(7), str(5)
memory usage: 10.8 KB

In [8]:
df1["till_semester_id"] = df1["till_semester_id"].fillna(99999)

In [9]:
df1[df1["version_number"].eq("230")]

,grade_id,grade_version_id,version_title_sl,version_number,from_percent,to_percent,points,from_semester_id,till_semester_id,finish_status,grade_show,active
3,974.111,3.111,القرار رقم 230,230,98.0,100.0,4.00,20162.0,99999.0,P,A+,A
7,975.111,3.111,القرار رقم 230,230,95.0,97.0,3.75,20162.0,99999.0,P,A,A
9,976.111,3.111,القرار رقم 230,230,90.0,94.0,3.50,20162.0,99999.0,P,A-,A
14,977.111,3.111,القرار رقم 230,230,85.0,89.0,3.25,20162.0,99999.0,P,B+,A
17,978.111,3.111,القرار رقم 230,230,80.0,84.0,3.00,20162.0,99999.0,P,B,A
22,979.111,3.111,القرار رقم 230,230,75.0,79.0,2.75,20162.0,99999.0,P,B-,A
27,980.111,3.111,القرار رقم 230,230,70.0,74.0,2.50,20162.0,99999.0,P,C+,A
30,981.111,3.111,القرار رقم 230,230,65.0,69.0,2.25,20162.0,99999.0,P,C,A
35,982.111,3.111,القرار رقم 230,230,60.0,64.0,2.00,20162.0,99999.0,P,C-,A
38,983.111,3.111,القرار رقم 230,230,55.0,59.0,1.75,20162.0,99999.0,P,D+,A
43,984.111,3.111,القرار رقم 230,230,50.0,54.0,1.50,20162.0,99999.0,P,D,A
46,985.111,3.111,القرار رقم 230,230,0.0,49.0,0.00,20162.0,99999.0,F,F,A
48,986.111,3.111,القرار رقم 230,230,0.0,0.0,0.00,20162.0,99999.0,W,W,A
52,987.111,3.111,القرار رقم 230,230,0.0,0.0,0.00,20162.0,99999.0,FA,Z,A
59,988.111,3.111,القرار رقم 230,230,0.0,0.0,0.00,20162.0,99999.0,I,I,A
63,989.111,3.111,القرار رقم 230,230,0.0,0.0,0.00,20162.0,99999.0,T,P,A
66,990.111,3.111,القرار رقم 230,230,0.0,0.0,0.00,20162.0,99999.0,IP,I,A
70,993.111,3.111,القرار رقم 230,230,0.0,0.0,0.00,20162.0,99999.0,NaN,F,A
74,991.111,3.111,القرار رقم 230,230,0.0,0.0,0.00,20162.0,99999.0,D,Z,A
76,992.111,3.111,القرار رقم 230,230,0.0,0.0,0.00,20162.0,99999.0,Z,Z,A
83,994.111,3.111,القرار رقم 230,230,0.0,0.0,0.00,20162.0,99999.0,ST,تدريب سريري,A
86,995.111,3.111,القرار رقم 230,230,0.0,0.0,0.00,20162.0,99999.0,FE,NaN,A
94,1006.101,3.111,القرار رقم 230,230,0.0,0.0,0.00,20162.0,99999.0,X,NaN,A
95,1004.111,3.111,القرار رقم 230,230,0.0,0.0,0.00,20162.0,99999.0,X,X,A
96,1006.101,3.111,القرار رقم 230,230,0.0,0.0,0.00,20162.0,99999.0,X,NaN,A
97,1004.111,3.111,القرار رقم 230,230,0.0,0.0,0.00,20162.0,99999.0,X,X,A
100,1005.111,3.111,القرار رقم 230,230,0.0,0.0,0.00,20162.0,99999.0,L,L,A

In [10]:
df1[df1['from_percent'].isna()]

,grade_id,grade_version_id,version_title_sl,version_number,from_percent,to_percent,points,from_semester_id,till_semester_id,finish_status,grade_show,active
89,1008.101,1.111,تأسيس الجامعة,1,NaN,NaN,NaN,20051.0,20111.0,X,X,A
91,1008.101,1.111,تأسيس الجامعة,1,NaN,NaN,NaN,20051.0,20111.0,X,X,A

In [11]:
df1.drop(df1[df1['from_percent'].isna()].index, inplace=True)

In [12]:
df['till_semester_id'].value_counts()

till_semester_id
20111.0    28
20162.0    26
Name: count, dtype: int64

In [13]:
df['version_number'].value_counts()

version_number
1      28
230    28
2      26
Name: count, dtype: int64

In [14]:
df1[df1['finish_status'].isna()]

,grade_id,grade_version_id,version_title_sl,version_number,from_percent,to_percent,points,from_semester_id,till_semester_id,finish_status,grade_show,active
2,999.111,1.111,تأسيس الجامعة,1,0.0,0.0,0.0,20051.0,20111.0,NaN,NaN,A
37,1000.111,1.111,تأسيس الجامعة,1,0.0,0.0,0.0,20051.0,20111.0,NaN,NaN,A
68,996.111,2.111,القرار الوزاري الموحد,2,0.0,0.0,0.0,20111.0,20162.0,NaN,F,A
69,1001.111,1.111,تأسيس الجامعة,1,0.0,0.0,0.0,20051.0,20111.0,NaN,NaN,A
70,993.111,3.111,القرار رقم 230,230,0.0,0.0,0.0,20162.0,99999.0,NaN,F,A
78,972.111,1.111,تأسيس الجامعة,1,0.0,0.0,0.0,20051.0,20111.0,NaN,NaN,A

In [15]:
df1 = df1.dropna(subset=["finish_status"]).copy()

print("Remaining null finish_status:", df1["finish_status"].isna().sum())

Remaining null finish_status: 0

In [16]:
df1.info()

<class 'pandas.DataFrame'>
Index: 71 entries, 1 to 103
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   grade_id          71 non-null     float64
 1   grade_version_id  71 non-null     float64
 2   version_title_sl  71 non-null     str
 3   version_number    71 non-null     str
 4   from_percent      71 non-null     float64
 5   to_percent        71 non-null     float64
 6   points            71 non-null     float64
 7   from_semester_id  71 non-null     float64
 8   till_semester_id  71 non-null     float64
 9   finish_status     71 non-null     str
 10  grade_show        66 non-null     str
 11  active            71 non-null     str
dtypes: float64(7), str(5)
memory usage: 9.7 KB

In [17]:
df1[df1['grade_id'].eq(	1008.101)]

Empty DataFrame
Columns: [grade_id, grade_version_id, version_title_sl, version_number, from_percent, to_percent, points, from_semester_id, till_semester_id, finish_status, grade_show, active]
Index: []

In [18]:
df1[df1['finish_status'].isna()]

Empty DataFrame
Columns: [grade_id, grade_version_id, version_title_sl, version_number, from_percent, to_percent, points, from_semester_id, till_semester_id, finish_status, grade_show, active]
Index: []

In [19]:
df1 = df1[df1["finish_status"].astype("string").str.strip().ne("1008.101")].copy()

In [20]:
df1 = df1[df1["grade_id"].ne(1006.101)].copy()

In [21]:
df1[df1['grade_show'].isna()]
df1=df1.reset_index()

In [22]:
df1[df1['grade_show'].isna()]

,index,grade_id,grade_version_id,version_title_sl,version_number,from_percent,to_percent,points,from_semester_id,till_semester_id,finish_status,grade_show,active
57,85,998.111,2.111,القرار الوزاري الموحد,2,0.0,0.0,0.0,20111.0,20162.0,FE,NaN,A
58,86,995.111,3.111,القرار رقم 230,230,0.0,0.0,0.0,20162.0,99999.0,FE,NaN,A
59,87,1003.111,1.111,تأسيس الجامعة,1,0.0,0.0,0.0,20051.0,20111.0,FE,NaN,A

In [23]:
df1['grade_show'].fillna("FE")

0     A+
1     A+
2      A
3      A
4      A
      ..
64     X
65     X
66     L
67     L
68     L
Name: grade_show, Length: 69, dtype: str

In [24]:
df1.reset_index()
df1=df1.drop(columns=['index'])

In [25]:
df1.columns

Index(['grade_id', 'grade_version_id', 'version_title_sl', 'version_number',
       'from_percent', 'to_percent', 'points', 'from_semester_id',
       'till_semester_id', 'finish_status', 'grade_show', 'active'],
      dtype='str')

In [26]:
df1.dtypes

grade_id            float64
grade_version_id    float64
version_title_sl        str
version_number          str
from_percent        float64
to_percent          float64
points              float64
from_semester_id    float64
till_semester_id    float64
finish_status           str
grade_show              str
active                  str
dtype: object

In [28]:
df1.to_csv(r"D:\AI\Real projects\Academic_Advisor\data\preprocessed\V_ACS_GRADE\v_acs_grade.csv",index=False)

In [29]:
df1.head()

,grade_id,grade_version_id,version_title_sl,version_number,from_percent,to_percent,points,from_semester_id,till_semester_id,finish_status,grade_show,active
0,673.111,2.111,القرار الوزاري الموحد,2,98.0,100.0,4.00,20111.0,20162.0,P,A+,A
1,974.111,3.111,القرار رقم 230,230,98.0,100.0,4.00,20162.0,99999.0,P,A+,A
2,674.111,2.111,القرار الوزاري الموحد,2,95.0,97.0,3.75,20111.0,20162.0,P,A,A
3,85.111,1.111,تأسيس الجامعة,1,90.0,100.0,4.00,20051.0,20111.0,P,A,A
4,975.111,3.111,القرار رقم 230,230,95.0,97.0,3.75,20162.0,99999.0,P,A,A