In [10]:
import pandas as pd

In [11]:
pd.set_option('display.max_columns',100)

In [12]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent  # if notebook is inside /notebooks
sys.path.append(str(PROJECT_ROOT))

from src.feature_engineering import run_feature_engineering_job, assert_no_leakage_columns

In [13]:
df=pd.read_parquet(r'D:\AI\Real projects\Academic_Advisor\data\audit\df_crg_add_acd.parquet')

In [14]:
df.shape

(761346, 26)

In [15]:
df.head()

,student_course_id,student_id,course_id,part_id,degree_id,faculty_id,grade_id,final_mark,course_credits,attempt_number,student_status_id,prev_gpa_points,gpa_points,start_agpa_points,start_total_in_courses,start_total_in_credits,semester_reg_credits,semester_reg_courses,semester_pass_credits,total_pass_credits,total_fail_credits,reg_total_semesters,start_level_name_pl,start_part_id,requirement_type_id,degree_requirement_credits_count
0,939272.111,10000.111,1016.111,20152,3.111,5.111,677.111,82,2.0,1,155348.111,2.41,2.36,2.41,6.0,17.0,18.0,6.0,18.0,17.0,0.0,2.0,First Year,20151,2,6
1,953865.111,10000.111,1017.111,20153,3.111,5.111,680.111,67,2.0,1,155349.111,2.36,2.25,2.39,12.0,35.0,9.0,3.0,9.0,35.0,0.0,3.0,Second Year,20151,2,6
2,1076397.111,10000.111,1019.111,20171,3.111,5.111,981.111,66,2.0,1,240678.111,2.17,1.76,2.28,27.0,80.0,17.0,6.0,17.0,80.0,0.0,6.0,Third year,20151,2,6
3,925010.111,10000.111,431.111,20152,3.111,5.111,677.111,83,3.0,1,155348.111,2.41,2.36,2.41,6.0,17.0,18.0,6.0,18.0,17.0,0.0,2.0,First Year,20151,3,65
4,901340.111,10000.111,432.111,20151,3.111,5.111,681.111,61,4.0,1,155347.111,<NA>,2.41,0.0,0.0,0.0,17.0,6.0,17.0,0.0,0.0,1.0,First Year,20151,3,65

In [16]:
df.columns

Index(['student_course_id', 'student_id', 'course_id', 'part_id', 'degree_id',
       'faculty_id', 'grade_id', 'final_mark', 'course_credits',
       'attempt_number', 'student_status_id', 'prev_gpa_points', 'gpa_points',
       'start_agpa_points', 'start_total_in_courses', 'start_total_in_credits',
       'semester_reg_credits', 'semester_reg_courses', 'semester_pass_credits',
       'total_pass_credits', 'total_fail_credits', 'reg_total_semesters',
       'start_level_name_pl', 'start_part_id', 'requirement_type_id',
       'degree_requirement_credits_count'],
      dtype='str')

In [18]:
result = run_feature_engineering_job(
    df,
    structural_zero_as_nan=True
)

Original df rows: 761346
Suffix consistency check: no conflicts detected.
No semester-level conflicts detected before aggregation.
Timeline diagnostics:

                                         value
student_degree_timeline_count          16927.0
part_sort_key_min                      20051.0
part_sort_key_max                      20252.0
first_semester_concept_mismatch_count   1200.0

Semester feature merge check:

            row_count
_merge
both           761346
left_only           0
right_only          0

Last valid GPA non-null ratio in semester frame: 0.8927297247593944
Last valid GPA non-null ratio after merge in df_model_audit: 0.8698620600883172
Previous-GPA chain diagnostics:

                                        row_count
prev_gpa_fill_source
raw_prev_gpa                               633622
zero_fallback                               95152
last_valid_gpa_before_current_semester      31782
start_agpa_points                             790

prev_gpa_fill_source null count: 0
prev_gpa_points_clean NaN count: 0
start_level_ord distribution:

                  count
start_level_ord
1                191689
2                171278
3                145068
4                119004
5                110306
6                 24001

Suspicious zero_fallback rows (returning student, no history): 346

,university_id,student_id,degree_id,part_id,course_id,prev_gpa_points,last_valid_gpa_before_current_semester,start_agpa_points,prev_gpa_points_clean,prev_gpa_fill_source,is_first_active_semester,is_first_row_in_timeline,no_previous_progress,start_level_ord
2063,111,10030.111,1.111,20161,1020.111,0.0,<NA>,0.0,0.0,zero_fallback,0,0,0,1
2068,111,10030.111,1.111,20161,956.111,0.0,<NA>,0.0,0.0,zero_fallback,0,0,0,1
24295,111,10353.111,13.111,20153,1020.111,0.0,<NA>,0.0,0.0,zero_fallback,0,1,0,2
24297,111,10353.111,13.111,20153,957.111,0.0,<NA>,0.0,0.0,zero_fallback,0,1,0,2
25831,111,10379.111,6.111,20152,431.111,0.0,<NA>,0.0,0.0,zero_fallback,0,0,0,2
25832,111,10379.111,6.111,20161,439.111,0.0,<NA>,0.0,0.0,zero_fallback,0,0,0,2
25834,111,10379.111,6.111,20152,501.111,0.0,<NA>,0.0,0.0,zero_fallback,0,0,0,2
25835,111,10379.111,6.111,20161,501.111,0.0,<NA>,0.0,0.0,zero_fallback,0,0,0,2
25837,111,10379.111,6.111,20152,513.111,0.0,<NA>,0.0,0.0,zero_fallback,0,0,0,2
25838,111,10379.111,6.111,20161,513.111,0.0,<NA>,0.0,0.0,zero_fallback,0,0,0,2
34189,111,10553.111,13.111,20152,957.111,0.0,<NA>,0.0,0.0,zero_fallback,0,1,0,1
34192,111,10553.111,13.111,20152,958.111,0.0,<NA>,0.0,0.0,zero_fallback,0,1,0,1
34194,111,10553.111,13.111,20152,959.111,0.0,<NA>,0.0,0.0,zero_fallback,0,1,0,1
34196,111,10553.111,13.111,20152,961.111,0.0,<NA>,0.0,0.0,zero_fallback,0,1,0,1
34198,111,10553.111,13.111,20152,963.111,0.0,<NA>,0.0,0.0,zero_fallback,0,1,0,1
34202,111,10553.111,13.111,20152,968.111,0.0,<NA>,0.0,0.0,zero_fallback,0,1,0,1
35568,111,10595.111,10.111,20161,121.111,0.0,<NA>,0.0,0.0,zero_fallback,0,0,0,1
35605,111,10595.111,10.111,20161,70.111,0.0,<NA>,0.0,0.0,zero_fallback,0,0,0,1
35607,111,10595.111,10.111,20161,71.111,0.0,<NA>,0.0,0.0,zero_fallback,0,0,0,1
35623,111,10595.111,10.111,20161,97.111,0.0,<NA>,0.0,0.0,zero_fallback,0,0,0,1
41342,111,10689.111,1.111,20172,1018.111,0.0,<NA>,0.0,0.0,zero_fallback,0,1,0,1
41348,111,10689.111,1.111,20172,296.111,0.0,<NA>,0.0,0.0,zero_fallback,0,1,0,1
41351,111,10689.111,1.111,20172,299.111,0.0,<NA>,0.0,0.0,zero_fallback,0,1,0,1
41353,111,10689.111,1.111,20172,301.111,0.0,<NA>,0.0,0.0,zero_fallback,0,1,0,1
41406,111,10689.111,1.111,20172,358.111,0.0,<NA>,0.0,0.0,zero_fallback,0,1,0,1

Advanced-standing cold-start zero_fallback rows (not suspicious): 2115

,university_id,student_id,degree_id,part_id,course_id,prev_gpa_points,last_valid_gpa_before_current_semester,start_agpa_points,prev_gpa_points_clean,prev_gpa_fill_source,is_first_active_semester,is_first_row_in_timeline,no_previous_progress,start_level_ord
1023,111,10018.111,2.111,20151,657.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
1030,111,10018.111,2.111,20151,665.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
1035,111,10018.111,2.111,20151,672.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
1099,111,10018.111,2.111,20151,955.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
1100,111,10018.111,2.111,20151,962.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
3417,111,10050.111,1.111,20151,1038.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
3418,111,10050.111,1.111,20151,296.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
3425,111,10050.111,1.111,20151,298.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
3426,111,10050.111,1.111,20151,299.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
3434,111,10050.111,1.111,20151,302.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
3438,111,10050.111,1.111,20151,304.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
3450,111,10050.111,1.111,20151,312.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
3453,111,10050.111,1.111,20151,313.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
9373,111,10131.111,1.111,20151,296.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
9375,111,10131.111,1.111,20151,298.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
9376,111,10131.111,1.111,20151,299.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
9380,111,10131.111,1.111,20151,303.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
9395,111,10131.111,1.111,20151,321.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
9438,111,10131.111,1.111,20151,955.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
9445,111,10132.111,1.111,20151,296.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
9447,111,10132.111,1.111,20151,298.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
9448,111,10132.111,1.111,20151,299.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
9452,111,10132.111,1.111,20151,303.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
9453,111,10132.111,1.111,20151,304.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
9511,111,10132.111,1.111,20151,955.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2

Semester stability conflicts (per column):

                                        conflict_count
prev_gpa_points_clean                                0
prev_gpa_fill_source                                 0
last_valid_gpa_before_current_semester               0
is_interruption_semester                             0
prev_semester_was_interruption                       0
prior_interruption_count                             0
consecutive_interruption_count                       0

Semester stability check: all columns stable within semester groups.
Last valid GPA non-null ratio in df_primary: 0.8647197507185527
Row counts:

                         row_count
original_df                 761346
df_model_audit              761346
df_primary                  727852
df_excluded_over_policy      33494

Final added or repaired columns:

                                      column
0                              university_id
1                      is_high_credit_course
2               over_policy_semester_credits
3               over_policy_semester_courses
4               exclude_over_policy_semester
5                    is_extreme_fail_history
6                  total_fail_credits_capped
7                   is_interruption_semester
8             prev_semester_was_interruption
9                   prior_interruption_count
10            consecutive_interruption_count
11                      no_previous_progress
12                  is_first_active_semester
13                  is_first_row_in_timeline
14    last_valid_gpa_before_current_semester
15                   prev_gpa_points_missing
16                      prev_gpa_points_zero
17                prev_gpa_invalid_zero_case
18                     prev_gpa_points_clean
19                      prev_gpa_fill_source
20     prev_gpa_replaced_due_to_invalid_zero
21          prev_gpa_actual_zero_performance
22                            model_prev_gpa
23                                 part_year
24                             part_semester
25                                start_year
26                            start_semester
27                       start_level_missing
28                           start_level_ord
29                  requirement_type_missing
30  degree_requirement_credits_count_missing
31               course_share_of_requirement
32                   requirement_size_bucket
33                  fail_credit_ratio_capped
34                         degree_course_key

In [19]:
df_model_audit = result["df_model_audit"]
df_primary = result["df_primary"]
df_excluded_over_policy = result["df_excluded_over_policy"]
diagnostics = result["diagnostics"]

In [20]:
diagnostics["row_counts"]

{'original_df': 761346,
 'df_model_audit': 761346,
 'df_primary': 727852,
 'df_excluded_over_policy': 33494}

In [21]:
diagnostics["prev_gpa_fill_source_counts"]

                                        row_count
prev_gpa_fill_source
raw_prev_gpa                               633622
zero_fallback                               95152
last_valid_gpa_before_current_semester      31782
start_agpa_points                             790

In [22]:
diagnostics["timeline_diagnostics"]

{'student_degree_timeline_count': 16927,
 'part_sort_key_min': 20051.0,
 'part_sort_key_max': 20252.0,
 'first_semester_concept_mismatch_count': 1200}

In [23]:
diagnostics["start_level_ord_counts"]

start_level_ord
1    191689
2    171278
3    145068
4    119004
5    110306
6     24001
Name: count, dtype: int64

In [24]:
diagnostics["suspicious_zero_fallback_count"]

346

In [25]:
diagnostics["advanced_standing_zero_fallback_count"]

2115

In [26]:
diagnostics["semester_stability_conflicts"]

{'prev_gpa_points_clean': 0,
 'prev_gpa_fill_source': 0,
 'last_valid_gpa_before_current_semester': 0,
 'is_interruption_semester': 0,
 'prev_semester_was_interruption': 0,
 'prior_interruption_count': 0,
 'consecutive_interruption_count': 0}

In [27]:
diagnostics["advanced_standing_zero_fallback_rows"].head(20)

,university_id,student_id,degree_id,part_id,course_id,prev_gpa_points,last_valid_gpa_before_current_semester,start_agpa_points,prev_gpa_points_clean,prev_gpa_fill_source,is_first_active_semester,is_first_row_in_timeline,no_previous_progress,start_level_ord
1023,111,10018.111,2.111,20151,657.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
1030,111,10018.111,2.111,20151,665.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
1035,111,10018.111,2.111,20151,672.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
1099,111,10018.111,2.111,20151,955.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
1100,111,10018.111,2.111,20151,962.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
3417,111,10050.111,1.111,20151,1038.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
3418,111,10050.111,1.111,20151,296.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
3425,111,10050.111,1.111,20151,298.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
3426,111,10050.111,1.111,20151,299.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
3434,111,10050.111,1.111,20151,302.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
3438,111,10050.111,1.111,20151,304.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
3450,111,10050.111,1.111,20151,312.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
3453,111,10050.111,1.111,20151,313.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
9373,111,10131.111,1.111,20151,296.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
9375,111,10131.111,1.111,20151,298.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
9376,111,10131.111,1.111,20151,299.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
9380,111,10131.111,1.111,20151,303.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
9395,111,10131.111,1.111,20151,321.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
9438,111,10131.111,1.111,20151,955.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2
9445,111,10132.111,1.111,20151,296.111,<NA>,<NA>,0.0,0.0,zero_fallback,1,1,1,2

In [28]:
len(diagnostics)

20

In [29]:
df1=df.head()

In [30]:
len(df1)

5

In [31]:
df1.to_csv(r"D:\AI\Real projects\Academic_Advisor\data\merged.csv")

In [32]:
primary = result["df_primary"]

In [33]:
len(primary)

727852

In [34]:
primary.columns

Index(['student_course_id', 'student_id', 'course_id', 'part_id', 'degree_id',
       'faculty_id', 'grade_id', 'final_mark', 'course_credits',
       'attempt_number', 'student_status_id', 'prev_gpa_points', 'gpa_points',
       'start_agpa_points', 'start_total_in_courses', 'start_total_in_credits',
       'semester_reg_credits', 'semester_reg_courses', 'semester_pass_credits',
       'total_pass_credits', 'total_fail_credits', 'reg_total_semesters',
       'start_level_name_pl', 'start_part_id', 'requirement_type_id',
       'degree_requirement_credits_count', 'university_id',
       'is_high_credit_course', 'over_policy_semester_credits',
       'over_policy_semester_courses', 'exclude_over_policy_semester',
       'is_extreme_fail_history', 'total_fail_credits_capped',
       'is_interruption_semester', 'prev_semester_was_interruption',
       'prior_interruption_count', 'consecutive_interruption_count',
       'no_previous_progress', 'is_first_active_semester',
       'is_first_row_in_timeline', 'last_valid_gpa_before_current_semester',
       'prev_gpa_points_missing', 'prev_gpa_points_zero',
       'prev_gpa_invalid_zero_case', 'prev_gpa_points_clean',
       'prev_gpa_fill_source', 'prev_gpa_replaced_due_to_invalid_zero',
       'prev_gpa_actual_zero_performance', 'model_prev_gpa', 'part_year',
       'part_semester', 'start_year', 'start_semester', 'start_level_missing',
       'start_level_ord', 'requirement_type_missing',
       'degree_requirement_credits_count_missing',
       'course_share_of_requirement', 'requirement_size_bucket',
       'fail_credit_ratio_capped', 'degree_course_key'],
      dtype='str')

In [35]:
primary['last_valid_gpa_before_current_semester']

0         2.41
1         2.36
2         2.17
3         2.41
4         <NA>
          ...
761341    <NA>
761342    0.86
761343    1.75
761344    2.58
761345    <NA>
Name: last_valid_gpa_before_current_semester, Length: 727852, dtype: Float64

In [36]:
history_cols = [
    "last_valid_gpa_before_current_semester",
    "is_interruption_semester",
    "prev_semester_was_interruption",
    "prior_interruption_count",
    "consecutive_interruption_count",
]

for c in history_cols:
    print("\n", c)
    print(primary[c].describe())
    print(primary[c].value_counts(dropna=False).head(10))

 last_valid_gpa_before_current_semester
count    629388.0
mean     2.184266
std      0.765133
min          0.08
25%          1.71
50%          2.27
75%          2.75
max           4.0
Name: last_valid_gpa_before_current_semester, dtype: Float64
last_valid_gpa_before_current_semester
<NA>    98464
2.5     12911
2.25    12832
2.0     11543
2.75    11361
3.0      8735
1.75     8485
1.5      7549
2.38     6601
2.63     6267
Name: count, dtype: Int64

 is_interruption_semester
count    727852.000000
mean          0.022208
std           0.147359
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_interruption_semester, dtype: float64
is_interruption_semester
0    711688
1     16164
Name: count, dtype: int64

 prev_semester_was_interruption
count    727852.000000
mean          0.024512
std           0.154632
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: prev_semester_was_interruption, dtype: float64
prev_semester_was_interruption
0    710011
1     17841
Name: count, dtype: int64

 prior_interruption_count
count    727852.000000
mean          0.218422
std           0.712390
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max          14.000000
Name: prior_interruption_count, dtype: float64
prior_interruption_count
0    631655
1     62391
2     18942
3      8212
4      3343
5      1487
6       809
7       417
8       279
9       114
Name: count, dtype: int64

 consecutive_interruption_count
count    727852.000000
mean          0.029167
std           0.204086
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           7.000000
Name: consecutive_interruption_count, dtype: float64
consecutive_interruption_count
0    710011
1     15445
2      1727
3       456
4       135
5        54
6        16
7         8
Name: count, dtype: int64

In [37]:
primary.to_parquet(r'D:\AI\Real projects\Academic_Advisor\data\audit\after_fet_eng.parquet')